[versions]
androidGradlePlugin = "7.4.2"
kotlin              = "1.9.22"
ksp                 = "1.9.22-1.0.17"
greendao            = "3.3.1"
therouter           = "1.2.2"
firebaseCrashlytics = "19.0.1"
googleFirebaseAnalytics = "22.0.1"
coreKtx = "1.3.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.7.0"
composeBom = "2023.08.00"
crashlyticsGradleVersion = "2.9.5"
googleServiceVersion = "4.4.1"
#mapboxVersion = "11.4.1"
mapboxVersion = "10.16.0"
mapboxSdkVersion = "6.5.0"
androidxAppcompatVersion = "1.4.2"
activityKtxVersion = "1.6.0"
fragmentKtxVersion = "1.6.0"
lifecycleExtensionVersion = "2.2.0"
lifecycleViewModelLiveDataVersion = "2.6.1"
lifecycleRuntimeVersion = "2.6.1"
material = "1.9.0"
activity = "1.5.0"
constraintlayout = "2.1.4"
amapVersion = "latest.integration"
djiAircraftProvided = "5.9.1"
coroutinesVersion = "1.7.1"
jtsCoreVersion = "1.18.2"
hiltAndroidGradlePluginVersion = "2.51.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library     = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-jvm          = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp                 = { id = "com.google.devtools.ksp", version.ref = "ksp" }
greendao            = { id = "org.greenrobot.greendao", version.ref = "greendao" }
therouter           = { id = "cn.therouter", version.ref = "therouter" }
googleServicePlugin = { id = "com.google.gms.google-services", version.ref = "googleServiceVersion" }
hiltAndroidGradlePlugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroidGradlePluginVersion" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
com-google-firebase-firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "googleFirebaseAnalytics" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref="crashlyticsGradleVersion" }
mapbox = { group = "com.mapbox.maps", name="android", version.ref="mapboxVersion" }
mapbox-sdk-service = { group = "com.mapbox.mapboxsdk", name="mapbox-sdk-services", version.ref="mapboxSdkVersion"}
mapbox-sdk-turf = { group = "com.mapbox.mapboxsdk", name="mapbox-sdk-turf", version.ref="mapboxSdkVersion"}
jts-core = { group = "org.locationtech.jts", name = "jts-core", version.ref = "jtsCoreVersion"}
androidx-appcompat = { group = "androidx.appcompat", name="appcompat", version.ref="androidxAppcompatVersion"}
androidx-activity-ktx = { group = "androidx.activity", name="activity-ktx", version.ref="activityKtxVersion"}
androidx-fragment-ktx = { group = "androidx.fragment", name="fragment-ktx", version.ref="fragmentKtxVersion"}
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "lifecycleRuntimeVersion"}
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name="lifecycle-viewmodel-ktx", version.ref="lifecycleViewModelLiveDataVersion"}
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name="lifecycle-extensions", version.ref="lifecycleExtensionVersion"}
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name="lifecycle-livedata-ktx", version.ref="lifecycleViewModelLiveDataVersion"}
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
amap-thridD = { group="com.amap.api", name="3dmap", version.ref="amapVersion" }
amap-location= { group="com.amap.api", name="location", version.ref="amapVersion" }
#com.dji:dji-sdk-v5-aircraft-provided:5.9.1
dji-aircraft-provided = { group = "com.dji", name = "dji-sdk-v5-aircraft-provided", version.ref = "djiAircraftProvided"}
dji-aircraft = { group = "com.dji", name = "dji-sdk-v5-aircraft", version.ref="djiAircraftProvided"}
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesVersion"}